### ISSUE TITLE
binstar-build is having trouble with metadatastore

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/conda-prescriptions#36]
the binstar-build workers are having trouble locating the CONDA_ENV_ environmental variable.  See this log output from the mac build worker for python=2.7 and OS X-64. Given the length of this log output, I've highlighted the actual error with three lines of asterisks 

```
Starting build, 552d81a7cbcbd45a2c7d4b75, latest/metadatastore#4.2
Setting alarm to terminate build after 216000 seconds
Building on worker 130-199-219-139.dhcp.bnl.gov (platform osx-64)
Starting build latest/metadatastore#4.2
Fetching build data
Wrote build data to build_data/552d81a7cbcbd45a2c7d4b75.tar.bz2
Running command: (iotimeout=60)
build_scripts/552d81a7cbcbd45a2c7d4b75.sh --api-token la-0617e718-e597-4290-b709-7afbcba7db53 --build-tarball /Users/ericdill/dev/python/conda-prescriptions/build_data/552d81a7cbcbd45a2c7d4b75.tar.bz2

[Setup Build]
Host: 130-199-219-139.dhcp.bnl.gov
Setting engine
conda create -p /Users/ericdill/dev/python/conda-prescriptions/build_envs/latest/metadatastore --quiet --yes python=2.7
conda-clean-build-dir
Removing conda build root /Users/ericdill/anaconda/conda-bld
Exception in thread io_loop:
Traceback (most recent call last):
  File "/Users/ericdill/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/ericdill/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ericdill/anaconda/lib/python2.7/site-packages/binstar_build_client/worker/utils/build_log.py", line 84, in _io_loop
    self.flush()
  File "/Users/ericdill/anaconda/lib/python2.7/site-packages/binstar_build_client/worker/utils/build_log.py", line 75, in flush
    self.bs.log_build_output(self.username, self.queue, self.worker_id, self.job_id, msg)
  File "/Users/ericdill/anaconda/lib/python2.7/site-packages/binstar_build_client/mixins/build_queue.py", line 42, in log_build_output
    self._check_response(res, [201])
  File "/Users/ericdill/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 160, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'OK: Request fulfilled, document follows ([POST] https://conda.nsls2.bnl.gov/api/build-worker/latest/mac-builder/552d648fcbcbd45a2c7d4832/jobs/552d81a7cbcbd45a2c7d4b75/log -> 200)', 200)

Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /Users/ericdill/dev/python/conda-prescriptions/build_envs/latest/metadatastore:

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-1     
    readline:   6.2-2       
    setuptools: 15.0-py27_0 
    sqlite:     3.8.4.1-1   
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

#
# To activate this environment, use:
# $ source activate /Users/ericdill/dev/python/conda-prescriptions/build_envs/latest/metadatastore
#
# To deactivate this environment, use:
# $ source deactivate
#
source activate /Users/ericdill/dev/python/conda-prescriptions/build_envs/latest/metadatastore
discarding /Users/ericdill/anaconda/bin from PATH
prepending /Users/ericdill/dev/python/conda-prescriptions/build_envs/latest/metadatastore/bin to PATH

[Fetching Build Source]
ls  -al /Users/ericdill/dev/python/conda-prescriptions/build_data/552d81a7cbcbd45a2c7d4b75.tar.bz2
-rw-r--r--  1 root  staff  626 Apr 14 17:07 /Users/ericdill/dev/python/conda-prescriptions/build_data/552d81a7cbcbd45a2c7d4b75.tar.bz2
Extracting Package
tar jxf /Users/ericdill/dev/python/conda-prescriptions/build_data/552d81a7cbcbd45a2c7d4b75.tar.bz2

[Before Script]
conda install -c https://conda.binstar.org/binstar binstar --yes
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /Users/ericdill/dev/python/conda-prescriptions/build_envs/latest/metadatastore:

The following NEW packages will be INSTALLED:

    binstar:         0.10.3-py27_0
    clyent:          0.3.4-py27_0 
    python-dateutil: 2.4.2-py27_0 
    pytz:            2015.2-py27_0
    pyyaml:          3.11-py27_0  
    requests:        2.6.0-py27_0 
    six:             1.9.0-py27_0 
    yaml:            0.1.4-1      

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
binstar config --set url https://conda.nsls2.bnl.gov/api
conda config --add channels latest
Skipping channels: latest, item already exists

[Script]
conda build . --python 2.7
Removing old build directory
Removing old work directory
BUILD START: metadatastore-v0.0.5-py27_0
Fetching package metadata: ........
Solving package specifications: .Cloning into bare repository '/Users/ericdill/anaconda/conda-bld/git_cache/__github.com_NSLS-II_metadatastore.git'...
Cloning into '/Users/ericdill/anaconda/conda-bld/work'...
done.
Note: checking out 'v0.0.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 412a105... REL : v0.0.5
+ /Users/ericdill/anaconda/envs/_build/bin/python setup.py install
0.5.0
running install
running bdist_egg
running egg_info
creating metadatastore.egg-info
writing metadatastore.egg-info/PKG-INFO
writing top-level names to metadatastore.egg-info/top_level.txt
writing dependency_links to metadatastore.egg-info/dependency_links.txt
writing manifest file 'metadatastore.egg-info/SOURCES.txt'
reading manifest file 'metadatastore.egg-info/SOURCES.txt'
writing manifest file 'metadatastore.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/metadatastore
copying metadatastore/__init__.py -> build/lib/metadatastore
copying metadatastore/api.py -> build/lib/metadatastore
copying metadatastore/commands.py -> build/lib/metadatastore
copying metadatastore/conf.py -> build/lib/metadatastore
copying metadatastore/document.py -> build/lib/metadatastore
copying metadatastore/odm_templates.py -> build/lib/metadatastore
creating build/lib/metadatastore/test
copying metadatastore/test/__init__.py -> build/lib/metadatastore/test
copying metadatastore/test/test_api.py -> build/lib/metadatastore/test
copying metadatastore/test/test_commands.py -> build/lib/metadatastore/test
copying metadatastore/test/test_sample_data.py -> build/lib/metadatastore/test
creating build/lib/metadatastore/utils
copying metadatastore/utils/__init__.py -> build/lib/metadatastore/utils
copying metadatastore/utils/testing.py -> build/lib/metadatastore/utils
creating build/lib/metadatastore/examples
copying metadatastore/examples/__init__.py -> build/lib/metadatastore/examples
creating build/lib/metadatastore/examples/sample_data
copying metadatastore/examples/sample_data/__init__.py -> build/lib/metadatastore/examples/sample_data
copying metadatastore/examples/sample_data/common.py -> build/lib/metadatastore/examples/sample_data
copying metadatastore/examples/sample_data/multisource_event.py -> build/lib/metadatastore/examples/sample_data
copying metadatastore/examples/sample_data/temperature_ramp.py -> build/lib/metadatastore/examples/sample_data
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/metadatastore
copying build/lib/metadatastore/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore
copying build/lib/metadatastore/api.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore
copying build/lib/metadatastore/commands.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore
copying build/lib/metadatastore/conf.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore
copying build/lib/metadatastore/document.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore
creating build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples
copying build/lib/metadatastore/examples/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples
creating build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data
copying build/lib/metadatastore/examples/sample_data/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data
copying build/lib/metadatastore/examples/sample_data/common.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data
copying build/lib/metadatastore/examples/sample_data/multisource_event.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data
copying build/lib/metadatastore/examples/sample_data/temperature_ramp.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data
copying build/lib/metadatastore/odm_templates.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore
creating build/bdist.macosx-10.5-x86_64/egg/metadatastore/test
copying build/lib/metadatastore/test/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/test
copying build/lib/metadatastore/test/test_api.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/test
copying build/lib/metadatastore/test/test_commands.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/test
copying build/lib/metadatastore/test/test_sample_data.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/test
creating build/bdist.macosx-10.5-x86_64/egg/metadatastore/utils
copying build/lib/metadatastore/utils/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/utils
copying build/lib/metadatastore/utils/testing.py -> build/bdist.macosx-10.5-x86_64/egg/metadatastore/utils
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/api.py to api.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/commands.py to commands.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/conf.py to conf.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/document.py to document.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data/common.py to common.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data/multisource_event.py to multisource_event.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/examples/sample_data/temperature_ramp.py to temperature_ramp.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/odm_templates.py to odm_templates.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/test/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/test/test_api.py to test_api.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/test/test_commands.py to test_commands.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/test/test_sample_data.py to test_sample_data.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/metadatastore/utils/testing.py to testing.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying metadatastore.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying metadatastore.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying metadatastore.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying metadatastore.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/metadatastore-0.5.0-py2.7.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing metadatastore-0.5.0-py2.7.egg
Copying metadatastore-0.5.0-py2.7.egg to /Users/ericdill/anaconda/envs/_build/lib/python2.7/site-packages
Adding metadatastore 0.5.0 to easy-install.pth file

Installed /Users/ericdill/anaconda/envs/_build/lib/python2.7/site-packages/metadatastore-0.5.0-py2.7.egg
Processing dependencies for metadatastore==0.5.0
Finished processing dependencies for metadatastore==0.5.0

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-1     
    readline:   6.2-2       
    setuptools: 15.0-py27_0 
    six:        1.9.0-py27_0
    sqlite:     3.8.4.1-1   
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Removing old work directory
checkout: u'v0.0.5'
==> git log -n1 <==

commit 412a105891b4b1ad637c861c79b0a5c8138bae2f
Author: Thomas A Caswell <tcaswell@bnl.gov>
Date:   Mon Apr 6 15:57:28 2015 -0400

    REL : v0.0.5
    
    - overhaul how configuration files are found, module no longer has
      default values for configuration
    - search on human readable times
    - API: Change to Event documents attributes
      - The Event documents are reorganized. Formerly,
        ``event.data`` returned a dictionary of ``(value, timestamp)``
        tuples.
    
           event.data = {'motor1': (value, timestamp),
                         'motor2': (value, timestamp)}
    
        Now, ``event.data`` is dictionary of the data
    
           event.data = {'motor1': value, 'motor2': value}
    
        and ``event.timestamp`` is a dictionary of the timestamps.
    
           event.timestamps = {'motor1': timestamp, 'motor2': timestamp}
    - API: All search functions now return generators
    - API: configuration yaml file now requires a ``timezone`` entry


==> git describe --tags --dirty <==

v0.0.5


==> git status <==

HEAD detached at v0.0.5
nothing to commit, working directory clean


Package: metadatastore-v0.0.5-py27_0
source tree in: /Users/ericdill/anaconda/conda-bld/work
found egg: /Users/ericdill/anaconda/envs/_build/lib/python2.7/site-packages/metadatastore-0.5.0-py2.7.egg
number of files: 2
Fixing permissions
Fixing permissions
BUILD END: metadatastore-v0.0.5-py27_0

*******************************************************************************
*******************************************************************************
*******************************************************************************

TEST START: metadatastore-v0.0.5-py27_0
**Fetching package metadata: ........
Solving package specifications: .===== testing package: metadatastore-v0.0.5-py27_0 =====
import: u'metadatastore'
Traceback (most recent call last):
  File "/Users/ericdill/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import metadatastore
  File "build/bdist.macosx-10.5-x86_64/egg/metadatastore/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/metadatastore/conf.py", line 62, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/metadatastore/conf.py", line 58, in load_configuration
KeyError: "The configuration field(s) ['timezone', 'host', 'port', 'database'] were not found in any file or environmental variable."

*******************************************************************************
*******************************************************************************
*******************************************************************************

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    metadatastore-v0.0.5       |           py27_0          44 KB

The following NEW packages will be INSTALLED:

    conda_etc:                1-0              
    metadatastore:            v0.0.5-py27_0    
    mongoengine:              v0.8.7-py27_0    
    nslsii_dev_configuration: 1-2              
    numpy:                    1.9.2-py27_0     
    openssl:                  1.0.1k-1         
    pandas:                   0.16.0-np19py27_1
    pip:                      6.1.1-py27_0     
    pymongo:                  2.8-py27_0       
    python:                   2.7.9-1          
    python-dateutil:          2.4.2-py27_0     
    pytz:                     2015.2-py27_0    
    pyyaml:                   3.11-py27_0      
    readline:                 6.2-2            
    setuptools:               15.0-py27_0      
    six:                      1.9.0-py27_0     
    sqlite:                   3.8.4.1-1        
    tk:                       8.5.18-0         
    yaml:                     0.1.4-1          
    zlib:                     1.2.8-0          

Fetching packages ...
metadatastore- 100% |###############################| Time: 0:00:00   2.04 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
TESTS FAILED: metadatastore-v0.0.5-py27_0
command exited with status 1
Exit BINSTAR_BUILD_RESULT=failure
Build script exited with code 12
[error] Build latest/metadatastore#4.2 failed 
Build Duration 36 seconds
```

**Comment by tacaswell** [comment]
See https://github.com/conda/conda-build/issues/364

**Comment by danielballan** [comment]
Closing since we have moved on from binstar-build
